version: '3.4'

services:
  srs.api:
    image: ${DOCKER_REGISTRY-}srsapi
    build:
      context: .
      dockerfile: Srs.Api/Dockerfile
    environment:
       SrsConfig__DbConnectionString: "Server=srs.db;Database=srs;User Id=sa;Password=123!@#qweQWE;Trust Server Certificate=True"
       SrsConfig__ShouldSeedDatabase: ${SrsConfig__ShouldSeedDatabase:-false}
    ports:
      - "20080:80"

  srs.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "21433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "123!@#qweQWE"
    volumes:
      - srs.db-data:/var/opt/mssql

volumes:
  srs.db-data: