version: '3.4'

services:
  srs.test.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "21434:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "123!@#qweQWE"
    volumes:
      - srs.test.db-data:/var/opt/mssql

volumes:
  srs.test.db-data: